import { DeleteOutlined, EditOutlined, EyeOutlined, PlusOutlined, ReloadOutlined, SearchOutlined } from '@ant-design/icons';
import { Button, Card, Descriptions, Drawer, Form, Image, Input, InputNumber, Popconfirm, Radio, Select, Space, Table, Tag, Typography, message } from 'antd';
import type { ColumnsType } from 'antd/es/table';
import { useEffect, useState } from 'react';
import { createProduct, deleteProduct, getProduct, listProducts, updateProduct } from '../api';
import type { Product, ProductPayload } from '../types';

export default function ProductsPage() {
  const [items, setItems] = useState<Product[]>([]); const [loading, setLoading] = useState(false);
  const [page, setPage] = useState(1); const [pageSize, setPageSize] = useState(10); const [total, setTotal] = useState(0);
  const [keyword, setKeyword] = useState(''); const [status, setStatus] = useState<0 | 1 | undefined>();
  const [drawer, setDrawer] = useState<'create' | 'edit' | 'detail' | null>(null); const [current, setCurrent] = useState<Product>(); const [form] = Form.useForm<ProductPayload>();
  const load = async () => { setLoading(true); try { const data = await listProducts({ page, pageSize, keyword: keyword || undefined, status }); setItems(data.items); setTotal(data.total); } catch { message.error('商品列表加载失败'); } finally { setLoading(false); } };
  useEffect(() => { void load(); }, [page, pageSize, status]);
  const openCreate = () => { setCurrent(undefined); form.resetFields(); form.setFieldsValue({ status: 1, stock: 0 }); setDrawer('create'); };
  const openProduct = async (record: Product, mode: 'edit' | 'detail') => { try { const detail = await getProduct(record.id); setCurrent(detail); form.setFieldsValue(detail); setDrawer(mode); } catch { message.error('商品详情加载失败'); } };
  const save = async () => { const values = await form.validateFields(); try { if (drawer === 'edit' && current) await updateProduct(current.id, values); else await createProduct(values); message.success(drawer === 'edit' ? '商品已更新' : '商品已创建'); setDrawer(null); await load(); } catch (error) { if ((error as { errorFields?: unknown }).errorFields) return; message.error('保存失败，请检查 SKU 是否重复'); } };
  const remove = async (id: string) => { try { await deleteProduct(id); message.success('商品已删除'); if (items.length === 1 && page > 1) setPage(page - 1); else await load(); } catch { message.error('删除失败'); } };
  const columns: ColumnsType<Product> = [
    { title: '商品', dataIndex: 'name', render: (_, row) => <Space>{row.imageUrl ? <Image width={44} height={44} preview={false} src={row.imageUrl} /> : <div className="image-placeholder">暂无</div>}<div><Typography.Text strong>{row.name}</Typography.Text><br /><Typography.Text type="secondary">{row.sku}</Typography.Text></div></Space> },
    { title: '价格', dataIndex: 'price', render: (value) => `¥${Number(value).toFixed(2)}` }, { title: '库存', dataIndex: 'stock' },
    { title: '状态', dataIndex: 'status', render: (value) => value === 1 ? <Tag color="success">上架</Tag> : <Tag>下架</Tag> },
    { title: '操作', key: 'actions', fixed: 'right', render: (_, row) => <Space><Button type="link" icon={<EyeOutlined />} onClick={() => openProduct(row, 'detail')}>查看</Button><Button type="link" icon={<EditOutlined />} onClick={() => openProduct(row, 'edit')}>编辑</Button><Popconfirm title="确定删除该商品？" onConfirm={() => remove(row.id)}><Button danger type="link" icon={<DeleteOutlined />}>删除</Button></Popconfirm></Space> },
  ];
  return <><Card title="商品管理" extra={<Button type="primary" icon={<PlusOutlined />} onClick={openCreate}>新增商品</Button>}><Space wrap className="filters"><Input allowClear value={keyword} onChange={(e) => setKeyword(e.target.value)} onPressEnter={() => { setPage(1); void load(); }} prefix={<SearchOutlined />} placeholder="商品名称 / SKU" /><Select allowClear value={status} onChange={(value) => { setPage(1); setStatus(value); }} placeholder="全部状态" options={[{ value: 1, label: '上架' }, { value: 0, label: '下架' }]} /><Button onClick={() => { setPage(1); void load(); }} icon={<SearchOutlined />}>查询</Button><Button icon={<ReloadOutlined />} onClick={() => { setKeyword(''); setStatus(undefined); setPage(1); }}>重置</Button></Space><Table rowKey="id" loading={loading} columns={columns} dataSource={items} scroll={{ x: 850 }} pagination={{ current: page, pageSize, total, showSizeChanger: true, showTotal: (value) => `共 ${value} 条`, onChange: (next, size) => { setPage(next); setPageSize(size); } }} /></Card>
    <Drawer width={520} open={drawer !== null} title={drawer === 'create' ? '新增商品' : drawer === 'edit' ? '编辑商品' : '商品详情'} onClose={() => setDrawer(null)} extra={drawer !== 'detail' && <Button type="primary" onClick={save}>保存</Button>}>
      {drawer === 'detail' && current ? <Descriptions column={1} bordered><Descriptions.Item label="商品图片">{current.imageUrl ? <Image width={160} src={current.imageUrl} /> : '暂无'}</Descriptions.Item><Descriptions.Item label="SKU">{current.sku}</Descriptions.Item><Descriptions.Item label="名称">{current.name}</Descriptions.Item><Descriptions.Item label="价格">¥{Number(current.price).toFixed(2)}</Descriptions.Item><Descriptions.Item label="库存">{current.stock}</Descriptions.Item><Descriptions.Item label="状态">{current.status ? '上架' : '下架'}</Descriptions.Item><Descriptions.Item label="描述">{current.description || '暂无'}</Descriptions.Item></Descriptions> : <Form form={form} layout="vertical"><Form.Item label="SKU" name="sku" rules={[{ required: true, message: '请输入 SKU' }, { max: 64 }]}><Input /></Form.Item><Form.Item label="商品名称" name="name" rules={[{ required: true, message: '请输入商品名称' }, { max: 200 }]}><Input /></Form.Item><Space size="large" align="start"><Form.Item label="价格" name="price" rules={[{ required: true, message: '请输入价格' }]}><InputNumber min={0} precision={2} prefix="¥" /></Form.Item><Form.Item label="库存" name="stock" rules={[{ required: true, message: '请输入库存' }]}><InputNumber min={0} precision={0} /></Form.Item></Space><Form.Item label="状态" name="status"><Radio.Group options={[{ label: '上架', value: 1 }, { label: '下架', value: 0 }]} /></Form.Item><Form.Item label="图片 URL" name="imageUrl" rules={[{ type: 'url', warningOnly: true }]}><Input /></Form.Item><Form.Item label="商品描述" name="description"><Input.TextArea rows={5} /></Form.Item></Form>}
    </Drawer></>;
}
