CREATE DATABASE IF NOT EXISTS mall DEFAULT CHARACTER SET utf8mb4 COLLATE utf8mb4_0900_ai_ci;
USE mall;

CREATE TABLE IF NOT EXISTS product (
  id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT COMMENT '商品 ID',
  sku VARCHAR(64) NOT NULL COMMENT '商品编码',
  name VARCHAR(200) NOT NULL COMMENT '商品名称',
  price DECIMAL(10, 2) UNSIGNED NOT NULL COMMENT '商品价格',
  stock INT UNSIGNED NOT NULL DEFAULT 0 COMMENT '库存',
  status TINYINT UNSIGNED NOT NULL DEFAULT 1 COMMENT '0 下架，1 上架',
  image_url VARCHAR(1000) NULL COMMENT '主图 URL',
  description TEXT NULL COMMENT '商品描述',
  created_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updated_at DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
  PRIMARY KEY (id),
  UNIQUE KEY uk_product_sku (sku),
  KEY idx_product_status_created (status, created_at),
  CONSTRAINT chk_product_status CHECK (status IN (0, 1))
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_0900_ai_ci COMMENT='商品';
